export const USER_DATA = 'USER_DATA'
export const OPEN_DROP_DOWN = 'OPEN_DROP_DOWN'
export const CLOSE_DROP_DOWN = 'CLOSE_DROP_DOWN'
export const LOAD_USERS = 'LOAD_USERS'
export const LOAD_TASKS = 'LOAD_TASKS'
export const SEND_FILTER = 'SEND_FILTER'
export const CLEAR_FILTER = 'CLEAR_FILTER'